---
- name: Set Host Facts
  set_fact:
    port: "{{ port | default(default_value, true) }}"

- name: Generate MongoDB Router Configuration
  template:
    src: mongos.conf.j2
    dest: /etc/mongos.conf
    owner: root
    group: root
    mode: 0644

- name: Generate MongoDB Router Service
  template:
    src: mongos.service.j2
    dest: /etc/systemd/system/mongos.service
    owner: root
    group: root
    mode: 0644

- name: Enable MongoDB Router Service
  systemd:
    name: mongos
    enabled: no
    state: started
    daemon_reload: yes

- name: Wait For MongoDB Router Service
  wait_for:
    port: "{{ port }}"
    delay: 5
    state: present

- name: Generate Script For Adding MongoDB ReplicaSet Node as Shards
  template:
    src: mongos-shards-join.js.j2
    dest: /tmp/mongos-shards-join.js
    owner: root
    group: root
    mode: 0644
  run_once: true

- name: Adding MongoDB ReplicaSet Node as Shards
  command: mongo admin --host {{ ip }} --port {{ port }} -u admin -p {{ mongo_admin_password }} /tmp/mongos-shards-join.js
  run_once: true
  
- name: Clean-up Generated Script For Adding MongoDB ReplicaSet Node as Shards
  file:
    path: /tmp/mongos-shards-join.js
    state: absent
  run_once: true
