---
- include: facts.yml

- include: mongo_services.yml

- include: mongo_files.yml

- include: mongo_dirs_childs.yml

- include: zfs_umounts.yml

- include: mongo_dirs_parents.yml

- include: mongo_packages.yml

- include: zfs_blocks.yml

- include: mongo_keys.yml
