---
- name: Disable MongoDB Node Service
  service:
    name: mongod
    enabled: no
    state: stopped
  when:
    - "not-found" not in mongod_service_info.stdout

- name: Disable MongoDB Router Service
  service:
    name: mongos
    enabled: no
    state: stopped
  when:
    - "not-found" not in mongos_service_info.stdout

- name: Remove MongoDB Router Service (Init)
  file:
    path: /etc/init.d/mongos
    state: absent
  when:
    - service_init_status.stat.islnk is defined
    - not service_init_status.stat.islnk

- name: Remove MongoDB Router Service (SystemD)
  file:
    path: /etc/systemd/system/mongos.service
    state: absent
  when:
    - service_init_status.stat.islnk is defined
    - service_init_status.stat.islnk
  notify: "Daemon Reload"
