---
- name: Uninstall MongoDB Packages (Percona)
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-server
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-mongos
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-shell
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-tools
  when:
    - mongo_distribution == 'percona'

- name: Uninstall MongoDB Repository (Percona)
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - percona-release
  when:
    - mongo_distribution == 'percona'
