---
- name: Remove MongoDB Parent Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/mongodb
  when:
    - not zfs_backend

- name: Remove MongoDB Run Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/run/mongodb
