---
- name: Get ZFS Dataset Lists
  command: zfs list
  register: zfs_dataset_lists

- name: Remove ZFS Dataset for MongoDB
  command: zfs destroy -fR {{ zfs_pool_name }}/mongodb
  when:
    - zfs_dataset_lists.stdout.find(zfs_pool_name ~ "/mongodb") != -1

- name: Get ZFS Pool Lists
  command: zpool list
  register: zfs_pool_lists
  when:
    - zfs_pool_wipe

- name: Remove ZFS Pool for MongoDB
  command: zpool destroy -f {{ zfs_pool_name }}
  when:
    - zfs_pool_lists.stdout.find(zfs_pool_name) != -1
    - zfs_pool_wipe

- name: Clean ZFS Block Device for MongoDB
  parted:
    device: "/dev/{{ zfs_block_device }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
    - "{{ zfs_block_info.partitions }}"
  when:
    - zfs_block_info.partitions is defined
    - zfs_block_wipe
