---
- include: facts.yml

- include: os_packages.yml

- include: openssl_packages.yml

- include: python_packages.yml

- include: zfs_packages.yml

- include: zfs_blocks.yml

- include: zfs_mounts.yml

- include: mongo_packages.yml

- include: mongo_dirs_parents.yml

- include: mongo_dirs_childs.yml

- include: mongo_keys.yml

- include: mongo_services.yml

- include: mongo_files.yml
