---
- include: facts.yml

- include: os_packages.yml

- include: python_packages.yml

- include: zfs_packages.yml
  when:
    - group_names == ['mongoc'] or group_names == ['mongod']
    - zfs_backend

- include: zfs_blocks.yml
  when:
    - group_names == ['mongoc'] or group_names == ['mongod']
    - zfs_backend

- include: zfs_mounts.yml
  when:
    - group_names == ['mongoc'] or group_names == ['mongod']
    - zfs_backend

- include: mongo_packages.yml

- include: mongo_dirs_parents.yml

- include: mongo_dirs_childs.yml

- include: mongo_keys.yml

- include: mongo_services.yml

- include: mongo_files.yml
