---
- include: facts.yml

- include: os_packages.yml

- include: python_packages.yml

- include: zfs_packages.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['mongoc'] or inventory_hostname in groups['mongoc']

- include: zfs_blocks.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['mongoc'] or inventory_hostname in groups['mongoc']

- include: zfs_mounts.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['mongoc'] or inventory_hostname in groups['mongoc']

- include: mongo_packages.yml

- include: mongo_dirs_parents.yml

- include: mongo_dirs_childs.yml

- include: mongo_keys.yml

- include: mongo_services.yml

- include: mongo_files.yml
