---
- name: Install MongoDB Keyring (MongoDB-ORG)
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    state: present
  when:
    - mongo_distribution == 'mongodb-org'

- name: Install MongoDB Repository (MongoDB-ORG)
  lineinfile:
    dest: /etc/apt/sources.list.d/mongodb-org-3.6.list
    line: "deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.6 multiverse"
    create: yes
    state: present
  when:
    - mongo_distribution == 'mongodb-org'

- name: Install MongoDB Packages (MongoDB-ORG)
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - mongodb-org
  when:
    - mongo_distribution == 'mongodb-org'
