---
- name: Create MongoDB Database Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mongo_file_owner }}"
    group: "{{ mongo_file_owner }}"
    recurse: true
  with_items:
    - /var/lib/mongodb/data
    - /var/lib/mongodb/log
    - /var/lib/mongodb/pki

- name: Symlink MongoDB Logs Directory
  file:
    src: /var/lib/mongodb/log
    dest: /var/log/mongodb
    owner: "{{ mongo_file_owner }}"
    group: "{{ mongo_file_owner }}"
    state: link
