---
- name: Install OpenSSL Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - openssl
  delegate_to: localhost
  run_once: true
