---
- name: Mount ZFS Dataset to MongoDB Directory
  mount:
    path: /var/lib/mongodb
    src: "/dev/zvol/{{ zfs_pool_name }}/mongodb"
    fstype: xfs
    opts: defaults
    passno: 2
    state: mounted
  when:
    - group_names == ['mongoc'] or group_names == ['mongod']
    - zfs_backend
