---
- name: Generate MongoDB Config Server Configuration
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: "{{ mongo_file_owner }}"
    group: "{{ mongo_file_owner }}"
    mode: 0644
